/*
  Simple DirectMedia Layer
  Copyright (C) 1997-2014 Sam Lantinga <slouken@libsdl.org>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/

#include "id_heads.h"
#include "SDL_scancode.h"

/*** Conversion tables ***/


static const uint16_t g_dosToSDL2ScancodeTable[] = {
	SDL_SCANCODE_UNKNOWN,
	SDL_SCANCODE_ESCAPE, // BE_ST_SC_ESC
	SDL_SCANCODE_1, // BE_ST_SC_1,
	SDL_SCANCODE_2, // BE_ST_SC_2,
	SDL_SCANCODE_3, // BE_ST_SC_3,
	SDL_SCANCODE_4, // BE_ST_SC_4,
	SDL_SCANCODE_5, // BE_ST_SC_5,
	SDL_SCANCODE_6, // BE_ST_SC_6,
	SDL_SCANCODE_7, // BE_ST_SC_7,
	SDL_SCANCODE_8, // BE_ST_SC_8,
	SDL_SCANCODE_9, // BE_ST_SC_9,
	SDL_SCANCODE_0, // BE_ST_SC_0,
	SDL_SCANCODE_MINUS, // BE_ST_SC_MINUS,
	SDL_SCANCODE_EQUALS, // BE_ST_SC_EQUALS,
	SDL_SCANCODE_BACKSPACE, // BE_ST_SC_BSPACE,
	SDL_SCANCODE_TAB, // BE_ST_SC_TAB,
	SDL_SCANCODE_Q, // BE_ST_SC_Q,
	SDL_SCANCODE_W, // BE_ST_SC_W,
	SDL_SCANCODE_E, // BE_ST_SC_E,
	SDL_SCANCODE_R, // BE_ST_SC_R,
	SDL_SCANCODE_T, // BE_ST_SC_T,
	SDL_SCANCODE_Y, // BE_ST_SC_Y,
	SDL_SCANCODE_U, // BE_ST_SC_U,
	SDL_SCANCODE_I, // BE_ST_SC_I,
	SDL_SCANCODE_O, // BE_ST_SC_O,
	SDL_SCANCODE_P, // BE_ST_SC_P,
	SDL_SCANCODE_LEFTBRACKET, // BE_ST_SC_LBRACKET,
	SDL_SCANCODE_RIGHTBRACKET, // BE_ST_SC_RBRACKET,
	SDL_SCANCODE_RETURN, // BE_ST_SC_ENTER,
	SDL_SCANCODE_LCTRL, // BE_ST_SC_LCTRL,
	SDL_SCANCODE_A, // BE_ST_SC_A,
	SDL_SCANCODE_S, // BE_ST_SC_S,
	SDL_SCANCODE_D, // BE_ST_SC_D,
	SDL_SCANCODE_F, // BE_ST_SC_F,
	SDL_SCANCODE_G, // BE_ST_SC_G,
	SDL_SCANCODE_H, // BE_ST_SC_H,
	SDL_SCANCODE_J, // BE_ST_SC_J,
	SDL_SCANCODE_K, // BE_ST_SC_K,
	SDL_SCANCODE_L, // BE_ST_SC_L,
	SDL_SCANCODE_SEMICOLON, // BE_ST_SC_SEMICOLON,
	SDL_SCANCODE_APOSTROPHE, // BE_ST_SC_QUOTE,
	SDL_SCANCODE_GRAVE, // BE_ST_SC_GRAVE,

	// Remap left shift to right shift
	SDL_SCANCODE_RSHIFT, // BE_ST_SC_LSHIFT,

	SDL_SCANCODE_BACKSLASH, // BE_ST_SC_BACKSLASH,
	SDL_SCANCODE_Z, // BE_ST_SC_Z,
	SDL_SCANCODE_X, // BE_ST_SC_X,
	SDL_SCANCODE_C, // BE_ST_SC_C,
	SDL_SCANCODE_V, // BE_ST_SC_V,
	SDL_SCANCODE_B, // BE_ST_SC_B,
	SDL_SCANCODE_N, // BE_ST_SC_N,
	SDL_SCANCODE_M, // BE_ST_SC_M,
	SDL_SCANCODE_COMMA, // BE_ST_SC_COMMA,
	SDL_SCANCODE_PERIOD, // BE_ST_SC_PERIOD,
	SDL_SCANCODE_SLASH, // BE_ST_SC_SLASH,
	SDL_SCANCODE_RSHIFT, // BE_ST_SC_RSHIFT,
	SDL_SCANCODE_KP_MULTIPLY, // BE_ST_SC_PRINTSCREEN / BE_ST_SC_KP_MULTIPLY,
	SDL_SCANCODE_LALT, // BE_ST_SC_LALT,
	SDL_SCANCODE_SPACE, // BE_ST_SC_SPACE,
	SDL_SCANCODE_CAPSLOCK, // BE_ST_SC_CAPSLOCK,
	SDL_SCANCODE_F1, // BE_ST_SC_F1,
	SDL_SCANCODE_F2, // BE_ST_SC_F2,
	SDL_SCANCODE_F3, // BE_ST_SC_F3,
	SDL_SCANCODE_F4, // BE_ST_SC_F4,
	SDL_SCANCODE_F5, // BE_ST_SC_F5,
	SDL_SCANCODE_F6, // BE_ST_SC_F6,
	SDL_SCANCODE_F7, // BE_ST_SC_F7,
	SDL_SCANCODE_F8, // BE_ST_SC_F8,
	SDL_SCANCODE_F9, // BE_ST_SC_F9,
	SDL_SCANCODE_F10, // BE_ST_SC_F10,
	SDL_SCANCODE_NUMLOCKCLEAR, // BE_ST_SC_NUMLOCK,
	SDL_SCANCODE_SCROLLLOCK, // BE_ST_SC_SCROLLLOCK,
	SDL_SCANCODE_HOME, // BE_ST_SC_KP_7,
	SDL_SCANCODE_UP, // BE_ST_SC_KP_8,
	SDL_SCANCODE_PAGEUP, // BE_ST_SC_KP_9,
	SDL_SCANCODE_KP_MINUS, // BE_ST_SC_KP_MINUS,
	SDL_SCANCODE_LEFT, // BE_ST_SC_KP_4,
	SDL_SCANCODE_KP_5, // BE_ST_SC_KP_5,
	SDL_SCANCODE_RIGHT, // BE_ST_SC_KP_6,
	SDL_SCANCODE_KP_PLUS, // BE_ST_SC_KP_PLUS,
	SDL_SCANCODE_END, // BE_ST_SC_KP_1,
	SDL_SCANCODE_DOWN, // BE_ST_SC_KP_2,
	SDL_SCANCODE_PAGEDOWN, // BE_ST_SC_KP_3,
	SDL_SCANCODE_INSERT, // BE_ST_SC_KP_0,
	SDL_SCANCODE_KP_PERIOD, // BE_ST_SC_KP_PERIOD,

	SDL_SCANCODE_UNKNOWN,
	SDL_SCANCODE_UNKNOWN,

	SDL_SCANCODE_NONUSBACKSLASH, // 0x56
	SDL_SCANCODE_F11, // BE_ST_SC_F11 = 0x57,
	SDL_SCANCODE_F12, // BE_ST_SC_F12 = 0x58,

	// Let's not map special pause (0xE1) scan code
};

static const uint8_t g_sdl2ToDOSScancodeTable[] = {
	0,
	0,
	0,
	0,
	BE_ST_SC_A, // SDL_SCANCODE_A
	BE_ST_SC_B, // SDL_SCANCODE_B
	BE_ST_SC_C, // SDL_SCANCODE_C
	BE_ST_SC_D, // SDL_SCANCODE_D
	BE_ST_SC_E, // SDL_SCANCODE_E
	BE_ST_SC_F, // SDL_SCANCODE_F
	BE_ST_SC_G, // SDL_SCANCODE_G
	BE_ST_SC_H, // SDL_SCANCODE_H
	BE_ST_SC_I, // SDL_SCANCODE_I
	BE_ST_SC_J, // SDL_SCANCODE_J
	BE_ST_SC_K, // SDL_SCANCODE_K
	BE_ST_SC_L, // SDL_SCANCODE_L
	BE_ST_SC_M, // SDL_SCANCODE_M
	BE_ST_SC_N, // SDL_SCANCODE_N
	BE_ST_SC_O, // SDL_SCANCODE_O
	BE_ST_SC_P, // SDL_SCANCODE_P
	BE_ST_SC_Q, // SDL_SCANCODE_Q
	BE_ST_SC_R, // SDL_SCANCODE_R
	BE_ST_SC_S, // SDL_SCANCODE_S
	BE_ST_SC_T, // SDL_SCANCODE_T
	BE_ST_SC_U, // SDL_SCANCODE_U
	BE_ST_SC_V, // SDL_SCANCODE_V
	BE_ST_SC_W, // SDL_SCANCODE_W
	BE_ST_SC_X, // SDL_SCANCODE_X
	BE_ST_SC_Y, // SDL_SCANCODE_Y
	BE_ST_SC_Z, // SDL_SCANCODE_Z

	BE_ST_SC_1, // SDL_SCANCODE_1
	BE_ST_SC_2, // SDL_SCANCODE_2
	BE_ST_SC_3, // SDL_SCANCODE_3
	BE_ST_SC_4, // SDL_SCANCODE_4
	BE_ST_SC_5, // SDL_SCANCODE_5
	BE_ST_SC_6, // SDL_SCANCODE_6
	BE_ST_SC_7, // SDL_SCANCODE_7
	BE_ST_SC_8, // SDL_SCANCODE_8
	BE_ST_SC_9, // SDL_SCANCODE_9
	BE_ST_SC_0, // SDL_SCANCODE_0

	BE_ST_SC_ENTER, // SDL_SCANCODE_RETURN
	BE_ST_SC_ESC, // SDL_SCANCODE_ESCAPE
	BE_ST_SC_BSPACE, // SDL_SCANCODE_BACKSPACE
	BE_ST_SC_TAB, // SDL_SCANCODE_TAB
	BE_ST_SC_SPACE, // SDL_SCANCODE_SPACE

	BE_ST_SC_MINUS, // SDL_SCANCODE_MINUS
	BE_ST_SC_EQUALS, // SDL_SCANCODE_EQUALS
	BE_ST_SC_LBRACKET, // SDL_SCANCODE_LEFTBRACKET
	BE_ST_SC_RBRACKET, // SDL_SCANCODE_RIGHTBRACKET
	BE_ST_SC_BACKSLASH, // SDL_SCANCODE_BACKSLASH

	0, // SDL_SCANCODE_NONUSHASH

	BE_ST_SC_SEMICOLON, // SDL_SCANCODE_SEMICOLON
	BE_ST_SC_QUOTE, // SDL_SCANCODE_APOSTROPHE
	BE_ST_SC_GRAVE, // SDL_SCANCODE_GRAVE
	BE_ST_SC_COMMA, // SDL_SCANCODE_COMMA
	BE_ST_SC_PERIOD, // SDL_SCANCODE_PERIOD
	BE_ST_SC_SLASH, // SDL_SCANCODE_SLASH

	BE_ST_SC_CAPSLOCK, // SDL_SCANCODE_CAPSLOCK

	BE_ST_SC_F1, // SDL_SCANCODE_F1
	BE_ST_SC_F2, // SDL_SCANCODE_F2
	BE_ST_SC_F3, // SDL_SCANCODE_F3
	BE_ST_SC_F4, // SDL_SCANCODE_F4
	BE_ST_SC_F5, // SDL_SCANCODE_F5
	BE_ST_SC_F6, // SDL_SCANCODE_F6
	BE_ST_SC_F7, // SDL_SCANCODE_F7
	BE_ST_SC_F8, // SDL_SCANCODE_F8
	BE_ST_SC_F9, // SDL_SCANCODE_F9
	BE_ST_SC_F10, // SDL_SCANCODE_F10
	BE_ST_SC_F11, // SDL_SCANCODE_F11
	BE_ST_SC_F12, // SDL_SCANCODE_F12

	BE_ST_SC_PRINTSCREEN, // SDL_SCANCODE_PRINTSCREEN
	BE_ST_SC_SCROLLLOCK, // SDL_SCANCODE_SCROLLLOCK
	BE_ST_SC_PAUSE, // SDL_SCANCODE_PAUSE
	BE_ST_SC_INSERT, // SDL_SCANCODE_INSERT
	BE_ST_SC_HOME, // SDL_SCANCODE_HOME
	BE_ST_SC_PAGEUP, // SDL_SCANCODE_PAGEUP
	BE_ST_SC_DELETE, // SDL_SCANCODE_DELETE
	BE_ST_SC_END, // SDL_SCANCODE_END
	BE_ST_SC_PAGEDOWN, // SDL_SCANCODE_PAGEDOWN
	BE_ST_SC_RIGHT, // SDL_SCANCODE_RIGHT
	BE_ST_SC_LEFT, // SDL_SCANCODE_LEFT
	BE_ST_SC_DOWN, // SDL_SCANCODE_DOWN
	BE_ST_SC_UP, // SDL_SCANCODE_UP

	BE_ST_SC_NUMLOCK, // SDL_SCANCODE_NUMLOCKCLEAR
	BE_ST_SC_KP_DIVIDE, // SDL_SCANCODE_KP_DIVIDE
	BE_ST_SC_KP_MULTIPLY, // SDL_SCANCODE_KP_MULTIPLY
	BE_ST_SC_KP_MINUS, // SDL_SCANCODE_KP_MINUS
	BE_ST_SC_KP_PLUS, // SDL_SCANCODE_KP_PLUS
	BE_ST_SC_KP_ENTER, // SDL_SCANCODE_KP_ENTER
	BE_ST_SC_KP_1, // SDL_SCANCODE_KP_1
	BE_ST_SC_KP_2, // SDL_SCANCODE_KP_2
	BE_ST_SC_KP_3, // SDL_SCANCODE_KP_3
	BE_ST_SC_KP_4, // SDL_SCANCODE_KP_4
	BE_ST_SC_KP_5, // SDL_SCANCODE_KP_5
	BE_ST_SC_KP_6, // SDL_SCANCODE_KP_6
	BE_ST_SC_KP_7, // SDL_SCANCODE_KP_7
	BE_ST_SC_KP_8, // SDL_SCANCODE_KP_8
	BE_ST_SC_KP_9, // SDL_SCANCODE_KP_9
	BE_ST_SC_KP_0, // SDL_SCANCODE_KP_0
	BE_ST_SC_KP_PERIOD, // SDL_SCANCODE_KP_PERIOD

	BE_ST_SC_LESSTHAN, // SDL_SCANCODE_NONUSBACKSLASH

	// SDL 2.0 scancodes 101 to 223 (either actually defined or not) follow...
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	BE_ST_SC_ENTER, // SDL_SCANCODE_SELECT (for Android, d-pad press)
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,

	// Remap left shift to right shift so it's usable in the control panel.
	// Let's also use the alt and ctrl defs, where there's no difference.

	BE_ST_SC_RCTRL, // SDL_SCANCODE_LCTRL
	BE_ST_SC_RSHIFT, // SDL_SCANCODE_LSHIFT
	BE_ST_SC_RALT, // SDL_SCANCODE_LALT

	0, // SDL_SCANCODE_LGUI

	BE_ST_SC_RCTRL, // SDL_SCANCODE_RCTRL
	BE_ST_SC_RSHIFT, // SDL_SCANCODE_RSHIFT
	BE_ST_SC_RALT, // SDL_SCANCODE_RALT
};


uint16_t RefKeen_TranslateScancodeFromDOSToSDL2(uint8_t scancode)
{
	if (scancode < BE_Cross_ArrayLen(g_dosToSDL2ScancodeTable))
		return g_dosToSDL2ScancodeTable[scancode];
	return 0;
}

uint8_t RefKeen_TranslateScancodeFromSDL2ToDOS(uint16_t scancode)
{
	if (scancode < BE_Cross_ArrayLen(g_sdl2ToDOSScancodeTable))
		return g_sdl2ToDOSScancodeTable[scancode];
	return 0;
}
