name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [win64, win32, macos, linux]
        lang_arg: [-DBUILD_AS_CPP=OFF, -DBUILD_AS_CPP=ON]
        include:
        - target: win64
          os: windows-latest
          pkg_update_cmd:
          pkg_install_cmd: vcpkg install sdl2 speexdsp --triplet=x64-windows
          platform_args: -A x64 -DCMAKE_TOOLCHAIN_FILE="$Env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
        - target: win32
          os: windows-latest
          pkg_update_cmd:
          pkg_install_cmd: vcpkg install sdl2 speexdsp --triplet=x86-windows
          platform_args: -A Win32 -DCMAKE_TOOLCHAIN_FILE="$Env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
        - target: macos
          os: macos-latest
          pkg_update_cmd: brew update
          pkg_install_cmd: brew install cmake sdl2 speexdsp
          platform_args:
        - target: linux
          os: ubuntu-latest
          pkg_update_cmd: sudo apt-get update
          pkg_install_cmd: sudo apt-get install cmake libsdl2-dev libspeexdsp-dev
          platform_args:
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        ${{ matrix.pkg_update_cmd }}
        ${{ matrix.pkg_install_cmd }}
    - name: Configure
      run: cmake -B build ${{ matrix.platform_args }} ${{ matrix.lang_arg }}
    - name: Build
      run: cmake --build build -j 2
