name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        lang_arg: [-DBUILD_AS_CPP=OFF, -DBUILD_AS_CPP=ON]
        include:
        - os: macos-latest
          pkg_update_cmd: brew update
          pkg_install_cmd: brew install cmake sdl2 speexdsp
        - os: ubuntu-latest
          pkg_update_cmd: sudo apt-get update
          pkg_install_cmd: sudo apt-get install cmake libsdl2-dev libspeexdsp-dev
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        ${{ matrix.pkg_update_cmd }}
        ${{ matrix.pkg_install_cmd }}
    - name: Configure
      run: cmake -B build ${{ matrix.lang_arg }}
    - name: Build
      run: cmake --build build -j 2
