name: CI
on: [push, pull_request]
jobs:
  macos-build:
    runs-on: macos-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew update
        brew install cmake sdl2 speexdsp
    - name: Configure
      run: cmake -B build
    - name: Build
      run: cmake --build build -j 2

  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cmake libsdl2-dev libspeexdsp-dev
    - name: Configure
      run: cmake -B build
    - name: Build
      run: cmake --build build -j 2
